# File: .github/workflows/build.yml

name: Build bugscanxOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build

      - name: Make Hook Executable
        run: chmod +x config/hooks/live/99-customizations.chroot

      # --- NEW STEP ADDED HERE ---
      # Clean any previous build artifacts and caches to ensure a fresh start
      - name: Clean Build Cache
        run: sudo lb clean --purge

      # Run the build process
      - name: Build the ISO
        run: sudo lb build

      # Upload the final ISO file
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bugscanxOS-1.0-amd64.iso
          path: live-image-amd64.hybrid.iso
