name: Build bugscanxOS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display Configuration File
        run: |
          echo "--- Contents of auto/config ---"
          cat auto/config
          echo "-----------------------------"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build

      - name: Make Hook Executable
        run: chmod +x config/hooks/live/99-customizations.chroot

      # --- UPDATED AND MORE AGGRESSIVE CLEANING STEP ---
      - name: Force Clean Build Cache
        run: |
          echo "Forcibly removing old build directories if they exist..."
          sudo rm -rf .build cache chroot binary
          echo "Running lb clean..."
          sudo lb clean --purge

      - name: Build the ISO
        run: sudo lb build

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bugscanxOS-1.0-amd64.iso
          path: live-image-amd64.hybrid.iso

