name: SSH Bot Hosting

on:
  workflow_dispatch: # manually trigger it from GitHub Actions tab

jobs:
  ssh-host:
    runs-on: ubuntu-latest
    timeout-minutes: 9999 # keep it alive for long time

    steps:
      - name: Set up environment
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server

      - name: Start SSH Server
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Create SSH User
        run: |
          sudo useradd -m botuser
          echo 'botuser:botpass' | sudo chpasswd
          sudo usermod -aG sudo botuser
          echo "✅ SSH user 'botuser' with password 'botpass' created."

      - name: Display SSH connection details
        run: |
          echo "=============================================="
          echo "🔑 SSH Connection Details"
          echo "Host: $(curl -s ifconfig.me)"
          echo "Username: botuser"
          echo "Password: botpass"
          echo "To connect, run:"
          echo "ssh botuser@$(curl -s ifconfig.me)"
          echo "=============================================="

      - name: Keep SSH Alive (Ping Google)
        run: |
          echo "🏃 Keeping runner alive... press Ctrl+C to stop workflow manually."
          while true; do
            ping -c 5 google.com
            sleep 30
          done
